### ISSUE TITLE
ERB gem is not loaded automatically, causing error

### ISSUE THREAD

**Issue by andhieka** [aegorov/yandex-translator#8]
When using yandex-translator in `irb`, running the following code:
```ruby
require 'yandex-translator'
api_key = "something-secret"
translator = Yandex::Translator.new(api_key)
translator.langs
```

will give error because ERB gem is not loaded automatically:

```
NameError: uninitialized constant HTTParty::HashConversions::ERB
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/hash_conversions.rb:33:in `normalize_param'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/hash_conversions.rb:15:in `block in to_params'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/hash_conversions.rb:15:in `each'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/hash_conversions.rb:15:in `map'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/hash_conversions.rb:15:in `to_params'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/request.rb:148:in `normalize_query'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/request.rb:129:in `body'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/request.rb:158:in `setup_raw_request'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty/request.rb:98:in `perform'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty.rb:521:in `perform_request'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/httparty-0.13.4/lib/httparty.rb:475:in `post'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/yandex-translator-0.3.1/lib/yandex/translator.rb:59:in `visit'
	from /Users/andhieka/.rvm/gems/ruby-2.1.2/gems/yandex-translator-0.3.1/lib/yandex/translator.rb:36:in `langs'
	from (irb):6
	from /Users/andhieka/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

This may be either bug from yandex-translator, or from HTTParty, not sure about that. Please consider fixing.

**Comment by aegorov** [comment]
it's look like was a bug of HTTParty - https://github.com/jnunemaker/httparty/pull/399
Fixed by change HTTParty version.
